
/**
 * Map from foodTags.js tags to Yelp API category aliases
 * Based on https://docs.developer.yelp.com/docs/resources-categories
 */
const foodTagsToYelpCategories = {
  // Cuisine types
  "French cuisine": "french",
  "Chinese cuisine": "chinese",
  "Japanese cuisine": "japanese",
  "Italian cuisine": "italian",
  "Greek cuisine": "greek",
  "Spanish cuisine": "spanish",
  "Korean cuisine": "korean",
  "Mediterranean cuisine": "mediterranean",
  "Lebanese cuisine": "mideastern",
  "Moroccan cuisine": "moroccan",
  "Turkish cuisine": "turkish",
  "Thai cuisine": "thai",
  "Fillipino cuisine": "filipino",
  "Indian cuisine": "indpak",
  "Cajun cuisine": "cajun",
  "Mexican cuisine": "mexican",
  "Caribbean cuisine": "caribbean",
  "German cuisine": "german",
  "Russian cuisine": "russian",
  "Hungarian cuisine": "hungarian",
  "American cuisine": "tradamerican",
  
  // Dietary preferences and eating styles
  "Spicy food lover": "hotandspicy",
  "Non-spicy foods only": "restaurants",
  "Dessert lover": "desserts",
  "Sweets lover": "desserts",
  "Locavore": "farmersmarket",
  "Clean eater": "healthy",
  "Low carbon eater": "sustainable",
  "Meat eater": "steakhouses",
  "Chicken lover": "chicken_wings",
  "Beef lover": "steakhouses",
  "Pork lover": "bbq",
  "No pork": "halal",
  "Lamb lover": "newamerican",
  "Duck lover": "french",
  "Seafood lover": "seafood",
  "Fish lover": "seafood",
  "Shrimp lover": "seafood",
  "Vegetarian": "vegetarian",
  "Ovo Vegetarian": "vegetarian",
  "Lacto Vegetarian": "vegetarian",
  "Vegan": "vegan",
  "Halal": "halal",
  "Pollotarian": "chicken_wings",
  "Flexitarian": "healthy",
  "Pescatarian": "seafood",
  "I eat everything": "restaurants",
  
  // Foodie types
  "Photographer foodie": "restaurants",
  "Home delivery foodie": "fooddelivery",
  "Adventurous foodie": "food",
  "Snobbish foodie": "gourmet",
  "Gastronomical foodie": "gourmet",
  "Forever broke foodie": "cheap",
  "Picky eater": "restaurants",
  
  // Establishment types
  "Restaurant": "restaurants",
  "Cafe": "cafes",
  "Bakery": "bakeries",
  "Boba shop": "bubbletea",
  
  // Meal types
  "Breakfast": "breakfast_brunch",
  "Lunch": "restaurants",
  "Dinner": "restaurants",
  "Dessert": "desserts",
  "Snacks": "food",
  "Drinks": "food",
  
  // Specific food items
  "Pizza": "pizza",
  "Sushi": "sushi",
  "Sashimi": "sushi",
  "Burgers": "burgers",
  "Tacos": "tacos",
  "Ramen": "ramen",
  "Pho": "vietnamese",
  "Vermicelli": "vietnamese",
  "Udon": "japanese",
  "Noodles": "noodles",
  "Tofu": "asianfusion",
  "Croissant": "bakeries",
  "Pasta": "italian",
  "Spaghetti": "italian",
  "Korean BBQ": "korean",
  "Steak": "steakhouses",
  "Dim sum": "dimsum",
  "Dumplings": "dimsum",
  "Soup dumplings": "dimsum",
  "Wontons": "chinese",
  "Gyoza": "japanese",
  "Hot pot": "hotpot",
  "Paella": "spanish",
  "BBQ": "bbq",
  "Skewers": "bbq",
  "Shawarma": "mideastern",
  "Rice": "asian",
  "Fried rice": "chinese",
  "Boba": "bubbletea",
  "Fruit tea": "bubbletea",
  "Taro": "bubbletea",
  "Thai tea": "thai",
  "Roti": "indpak",
  "Curry": "indpak",
  "Indian curry": "indpak",
  "Japanese curry": "japanese",
  "Thai curry": "thai",
  "French fries": "hotdogs",
  "Mochi": "japanese",
  "Cake": "cakeshop",
  "Cupcakes": "cupcakes",
  "Risotto": "italian",
  "Lasagna": "italian",
  "Kimchi": "korean",
  "Onigiri": "japanese",
  "Quiche": "french",
  "Brownies": "bakeries",
  "Fried chicken": "southern",
  "Salmon": "seafood",
  "Soba": "japanese",
  "Nachos": "mexican",
  "Biryani": "indpak",
  "Shabu-shabu": "japanese",
  "Mac and cheese": "comfortfood",
  "Burritos": "mexican",
  "Tamal": "mexican",
  "Miso": "japanese",
  "Soup": "soup",
  "Salad": "salad",
  "Cheese": "cheese",
  "Wasabi": "japanese",
  "Chutneys": "indpak",
  "Tonkotsu": "ramen",
  "Guacamole": "mexican",
  "Quesadilla": "mexican",
  "Doughnuts": "donuts",
  "Naan": "indpak",
  "Bulgogi": "korean",
  "Bibimbap": "korean",
  "Cookies": "bakeries",
  "Baguettes": "bakeries",
  "Fajitas": "mexican",
  "Ceviche": "latin",
  "Churrasco": "brazilian",
  "Pad thai": "thai",
  "Fish and chips": "british",
  "Milkshakes": "icecream",
  "Mole": "mexican",
  "Spring rolls": "vietnamese",
  "Macarons": "french",
  "Churros": "spanish",
  "Borek": "turkish",
  "Bruschetta": "italian",
  "Pie": "bakeries",
  "Dondurma": "turkish",
  "Chorizos": "spanish",
  "Durian": "bubbletea",
  "Yogurt": "yogurt",
  "Sarma": "turkish",
  
  // Flavors
  "Strawberry": "food",
  "Chocolate": "chocolate",
  "Vanilla": "desserts",
  "Lemon": "desserts",
  "Lime": "desserts",
  "Mint": "desserts",
  "Banana": "desserts",
  "Coconut": "desserts",
  "Cookies and cream": "icecream",
  "Caramel": "desserts",
  "Chocolate chip": "bakeries",
  "Green tea": "tea",
  "Raspberry": "desserts",
  "Orange": "juicebars",
  "Funfetti": "cakeshop",
  "Cherry": "desserts",
  "Watermelon": "juicebars",
  "Grape": "juicebars",
  "Mango": "juicebars",
  "Peppermint": "desserts",
  "Pistachio": "desserts",
  "Blue moon": "icecream",
  "Gold": "desserts",
  "Fudge": "chocolate",
  "Cheesecake": "desserts",
  "Tiramisu": "italian",
  "Mousse": "desserts",
  "Red velvet": "cakeshop",
  "Cream cheese": "cakeshop",
  "Apple": "desserts",
  "Pineapple": "desserts",
  "Butter cream": "cakeshop",
  "Carrot": "desserts",
  "Blueberry": "desserts",
  "Pumpkin": "desserts",
  "Chestnut": "desserts",
  "Sponge cake": "cakeshop",
  "Coffee": "coffee",
  "Raisin": "desserts",
  "Grapefruit": "juicebars",
  
  // Coffee types
  "Espresso": "coffee",
  "Americano": "coffee",
  "Black coffee": "coffee",
  "Cappuccino": "coffee",
  "Latte": "coffee",
  "Macchiato": "coffee",
  "Mocha": "coffee",
  "Frappe": "coffee",
  "Iced coffee": "coffee"
};

export default foodTagsToYelpCategories;