
/**
 * Map from foodTags.js tags to Yelp API category aliases
 * Based on https://docs.developer.yelp.com/docs/resources-categories
 */
const foodTagsToYelpCategories = {
  // Cuisine types
  "French cuisine": "french",
  "Chinese cuisine": "chinese",
  "Japanese cuisine": "japanese",
  "Italian cuisine": "italian",
  "Greek cuisine": "greek",
  "Spanish cuisine": "spanish",
  "Korean cuisine": "korean",
  "Mediterranean cuisine": "mediterranean",
  "Lebanese cuisine": "mideastern",
  "Moroccan cuisine": "moroccan",
  "Turkish cuisine": "turkish",
  "Thai cuisine": "thai",
  "Fillipino cuisine": "filipino",
  "Indian cuisine": "indpak",
  "Cajun cuisine": "cajun",
  "Mexican cuisine": "mexican",
  "Caribbean cuisine": "caribbean",
  "German cuisine": "german",
  "Russian cuisine": "russian",
  "Hungarian cuisine": "hungarian",
  "American cuisine": "tradamerican",
  
  // Dietary preferences and eating styles
  "Spicy food lover": "hotandspicy",
  "Non-spicy foods only": "restaurants",
  "Dessert lover": "desserts",
  "Sweets lover": "desserts",
  "Locavore": "farmersmarket",
  "Clean eater": "healthy",
  "Low carbon eater": "sustainable",
  "Meat eater": "steakhouses",
  "Chicken lover": "chicken_wings",
  "Beef lover": "steakhouses",
  "Pork lover": "bbq",
  "No pork": "halal",
  "Lamb lover": "newamerican",
  "Duck lover": "french",
  "Seafood lover": "seafood",
  "Fish lover": "seafood",
  "Shrimp lover": "seafood",
  "Vegetarian": "vegetarian",
  "Ovo Vegetarian": "vegetarian",
  "Lacto Vegetarian": "vegetarian",
  "Vegan": "vegan",
  "Halal": "halal",
  "Pollotarian": "chicken_wings",
  "Flexitarian": "healthy",
  "Pescatarian": "seafood",
  "I eat everything": "restaurants",
  
  // Foodie types
  "Photographer foodie": "restaurants",
  "Home delivery foodie": "fooddelivery",
  "Adventurous foodie": "food",
  "Snobbish foodie": "gourmet",
  "Gastronomical foodie": "gourmet",
  "Forever broke foodie": "cheap",
  "Picky eater": "restaurants",
  
  // Establishment types
  "Restaurant": "restaurants",
  "Cafe": "cafes",
  "Bakery": "bakeries",
  "Boba shop": "bubbletea",
  
  // Meal types
  "Breakfast": "breakfast_brunch",
  "Lunch": "restaurants",
  "Dinner": "restaurants",
  "Dessert": "desserts",
  "Snacks": "food",
  "Drinks": "food",
  
  // Specific food items
  "Pizza": "pizza",
  "Sushi": "sushi",
  "Sashimi": "sushi",
  "Burgers": "burgers",
  "Tacos": "tacos",
  "Ramen": "ramen",
  "Pho": "vietnamese",
  "Vermicelli": "vietnamese",
  "Udon": "japanese",
  "Noodles": "noodles",
  "Tofu": "asianfusion",
  "Croissant": "bakeries",
  "Pasta": "italian",
  "Spaghetti": "italian",
  "Korean BBQ": "korean",
  "Steak": "steakhouses",
  "Dim sum": "dimsum",
  "Dumplings": "dimsum",
  "Soup dumplings": "dimsum",
  "Wontons": "chinese",
  "Gyoza": "japanese",
  "Hot pot": "hotpot",
  "Paella": "spanish",
  "BBQ": "bbq",
  "Skewers": "bbq",
  "Shawarma": "mideastern",
  "Rice": "asian",
  "Fried rice": "chinese",
  "Boba": "bubbletea",
  "Fruit tea": "bubbletea",
  "Taro": "bubbletea",
  "Thai tea": "thai",
  "Roti": "indpak",
  "Curry": "indpak",
  "Indian curry": "indpak",
  "Japanese curry": "japanese",
  "Thai curry": "thai",
  "French fries": "hotdogs",
  "Mochi": "japanese",
  "Cake": "cakeshop",
  "Cupcakes": "cupcakes",
  "Risotto": "italian",
  "Lasagna": "italian",
  "Kimchi": "korean",
  "Onigiri": "japanese",
  "Quiche": "french",
  "Brownies": "bakeries",
  "Fried chicken": "southern",
  "Salmon": "seafood",
  "Soba": "japanese",
  "Nachos": "mexican",
  "Biryani": "indpak",
  "Shabu-shabu": "japanese",
  "Mac and cheese": "comfortfood",
  "Burritos": "mexican",
  "Tamal": "mexican",
  "Miso": "japanese",
  "Soup": "soup",
  "Salad": "salad",
  "Cheese": "cheese",
  "Wasabi": "japanese",
  "Chutneys": "indpak",
  "Tonkotsu": "ramen",
  "Guacamole": "mexican",
  "Quesadilla": "mexican",
  "Doughnuts": "donuts",
  "Naan": "indpak",
  "Bulgogi": "korean",
  "Bibimbap": "korean",
  "Cookies": "bakeries",
  "Baguettes": "bakeries",
  "Fajitas": "mexican",
  "Ceviche": "latin",
  "Churrasco": "brazilian",
  "Pad thai": "thai",
  "Fish and chips": "british",
  "Milkshakes": "icecream",
  "Mole": "mexican",
  "Spring rolls": "vietnamese",
  "Macarons": "french",
  "Churros": "spanish",
  "Borek": "turkish",
  "Bruschetta": "italian",
  "Pie": "bakeries",
  "Dondurma": "turkish",
  "Chorizos": "spanish",
  "Durian": "bubbletea",
  "Yogurt": "yogurt",
  "Sarma": "turkish",
  
  // Flavors
  "Strawberry": "food",
  "Chocolate": "chocolate",
  "Vanilla": "desserts",
  "Lemon": "desserts",
  "Lime": "desserts",
  "Mint": "desserts",
  "Banana": "desserts",
  "Coconut": "desserts",
  "Cookies and cream": "icecream",
  "Caramel": "desserts",
  "Chocolate chip": "bakeries",
  "Green tea": "tea",
  "Raspberry": "desserts",
  "Orange": "juicebars",
  "Funfetti": "cakeshop",
  "Cherry": "desserts",
  "Watermelon": "juicebars",
  "Grape": "juicebars",
  "Mango": "juicebars",
  "Peppermint": "desserts",
  "Pistachio": "desserts",
  "Blue moon": "icecream",
  "Gold": "desserts",
  "Fudge": "chocolate",
  "Cheesecake": "desserts",
  "Tiramisu": "italian",
  "Mousse": "desserts",
  "Red velvet": "cakeshop",
  "Cream cheese": "cakeshop",
  "Apple": "desserts",
  "Pineapple": "desserts",
  "Butter cream": "cakeshop",
  "Carrot": "desserts",
  "Blueberry": "desserts",
  "Pumpkin": "desserts",
  "Chestnut": "desserts",
  "Sponge cake": "cakeshop",
  "Coffee": "coffee",
  "Raisin": "desserts",
  "Grapefruit": "juicebars",
  
  // Coffee types
  "Espresso": "coffee",
  "Americano": "coffee",
  "Black coffee": "coffee",
  "Cappuccino": "coffee",
  "Latte": "coffee",
  "Macchiato": "coffee",
  "Mocha": "coffee",
  "Frappe": "coffee",
  "Iced coffee": "coffee",

    "Acai Bowls": "acaibowls",
    "Afghan": "afghani",
    "African": "african",
    "American (New)": "newamerican",
    "American (Traditional)": "tradamerican",
    "Arabic": "arabian",
    "Argentine": "argentine",
    "Asian Fusion": "asianfusion",
    "Australian": "australian",
    "Austrian": "austrian",
    "Bagels": "bagels",
    "Bakeries": "bakeries",
    "Bangladeshi": "bangladeshi",
    "Barbeque": "bbq",
    "Basque": "basque",
    "Beer, Wine & Spirits": "beer_and_wine",
    "Belgian": "belgian",
    "Beverage Store": "beverage_stores",
    "Bistros": "bistros",
    "Brasseries": "brasseries",
    "Brazilian": "brazilian",
    "Breakfast & Brunch": "breakfast_brunch",
    "Breweries": "breweries",
    "British": "british",
    "Bubble Tea": "bubbletea",
    "Buffets": "buffets",
    "Bulgarian": "bulgarian",
    "Burgers": "burgers",
    "Burmese": "burmese",
    "Butcher": "butcher",
    "Cafes": "cafes",
    "Cafeteria": "cafeteria",
    "Cajun/Creole": "cajun",
    "Cambodian": "cambodian",
    "Caribbean": "caribbean",
    "Cheesesteaks": "cheesesteaks",
    "Chicken Shop": "chickenshop",
    "Chicken Wings": "chicken_wings",
    "Chinese": "chinese",
    "Coffee & Tea": "coffee",
    "Coffee Roasteries": "coffeeroasteries",
    "Comfort Food": "comfortfood",
    "Convenience Stores": "convenience",
    "Creperies": "creperies",
    "Cuban": "cuban",
    "Cupcakes": "cupcakes",
    "Custom Cakes": "customcakes",
    "Delicatessen": "delicatessen",
    "Delis": "delis",
    "Desserts": "desserts",
    "Dim Sum": "dimsum",
    "Diners": "diners",
    "Distilleries": "distilleries",
    "Do-It-Yourself Food": "diyfood",
    "Donuts": "donuts",
    "Ethiopian": "ethiopian",
    "Farmers Market": "farmersmarket",
    "Fast Food": "hotdogs",
    "Filipino": "filipino",
    "Fish & Chips": "fishnchips",
    "Food Delivery Services": "fooddeliveryservices",
    "Food Stands": "foodstands",
    "Food Trucks": "foodtrucks",
    "French": "french",
    "Gastropubs": "gastropubs",
    "Gelato": "gelato",
    "German": "german",
    "Gluten-Free": "gluten_free",
    "Greek": "greek",
    "Grocery": "grocery",
    "Halal": "halal",
    "Hawaiian": "hawaiian",
    "Himalayan/Nepalese": "himalayan",
    "Honduran": "honduran",
    "Hong Kong Style Cafe": "hkcafe",
    "Hot Dogs": "hotdog",
    "Hot Pot": "hotpot",
    "Hungarian": "hungarian",
    "Ice Cream & Frozen Yogurt": "icecream",
    "Indian": "indpak",
    "Indonesian": "indonesian",
    "International": "international",
    "Irish": "irish",
    "Italian": "italian",
    "Japanese": "japanese",
    "Juice Bars & Smoothies": "juicebars",
    "Kebab": "kebab",
    "Korean": "korean",
    "Kosher": "kosher",
    "Laotian": "laotian",
    "Latin American": "latin",
    "Live/Raw Food": "raw_food",
    "Malaysian": "malaysian",
    "Mediterranean": "mediterranean",
    "Mexican": "mexican",
    "Middle Eastern": "mideastern",
    "Modern European": "modern_european",
    "Mongolian": "mongolian",
    "Moroccan": "moroccan",
    "Nicaraguan": "nicaraguan",
    "Noodles": "noodles",
    "Organic Stores": "organic_stores",
    "Pakistani": "pakistani",
    "Pan Asian": "panasian",
    "Persian/Iranian": "persian",
    "Peruvian": "peruvian",
    "Pizza": "pizza",
    "Polish": "polish",
    "Portuguese": "portuguese",
    "Ramen": "ramen",
    "Russian": "russian",
    "Salad": "salad",
    "Sandwiches": "sandwiches",
    "Scandinavian": "scandinavian",
    "Seafood": "seafood",
    "Singaporean": "singaporean",
    "Smokehouse": "smokehouse",
    "Soul Food": "soulfood",
    "Soup": "soup",
    "Southern": "southern",
    "Spanish": "spanish",
    "Specialty Food": "gourmet",
    "Sri Lankan": "srilankan",
    "Steakhouses": "steak",
    "Sushi Bars": "sushi",
    "Syrian": "syrian",
    "Taiwanese": "taiwanese",
    "Tapas Bars": "tapas",
    "Tapas/Small Plates": "tapasmallplates",
    "Tea Rooms": "tea",
    "Tex-Mex": "tex-mex",
    "Thai": "thai",
    "Turkish": "turkish",
    "Ukrainian": "ukrainian",
    "Vegan": "vegan",
    "Vegetarian": "vegetarian",
    "Vietnamese": "vietnamese",
    "Waffles": "waffles",
    "Wineries": "wineries",
    "Wine Bars": "wine_bars",
    "Wine Tasting Room": "winetastingroom"
};

export default foodTagsToYelpCategories;